# Generated by Django 5.2.7 on 2025-11-07 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='deprature',
            new_name='departure',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='deprature_time',
            new_name='departure_time',
        ),
    ]
