# Generated by Django 5.2.7 on 2025-11-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_author_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='book',
            name='number_of_copies',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='book',
            name='published_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
